### ISSUE TITLE
validCount too much!

### ISSUE THREAD

**Issue by 1343464520** [troyseed/C_rknn_ssd_multithread#1]
![rk_ssd_error](https://user-images.githubusercontent.com/24668916/72242707-098ac280-3625-11ea-9051-c68ab9ae7ac2.png)
我做的是检测行人，只有一类。请问这个这个报错怎么修改呢？谢谢大佬！

**Comment by troyseed** [comment]
我实测了一下，当前代码在最新固件上运行是正常的，你应该是有做了一些修改。是否更换了模型，是否重新后处理函数，后处理需要和你的模型输出对应上才行。
需要修改的代码都在ssd_demo.cpp里面。

**Comment by 1343464520** [comment]
固件用是1.2.0版的，模型是用caffe版本的mobilenet-ssd转换成rk的，只是把类别修改为2，后处理都是用的您的代码，不知道问题在哪。。方便请留个q吗，谢谢！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "troyseed"<notifications@github.com&gt;; 
发送时间: 2020年1月14日(星期二) 上午8:50
收件人: "troyseed/toybrick_ssd_multithread"<toybrick_ssd_multithread@noreply.github.com&gt;; 
抄送: "科比"<1343464520@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [troyseed/toybrick_ssd_multithread] validCount too much! (#1)




我实测了一下，当前代码在最新固件上运行是正常的，你应该是有做了一些修改。是否更换了模型，是否重新后处理函数，后处理需要和你的模型输出对应上才行。
 需要修改的代码都在ssd_demo.cpp里面。

**Comment by troyseed** [comment]
demo只是提供个参考，还有一个便捷的框架，后处理需要自己处理。
